CREATE TABLE [accounts].[Account]
(
	[Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Account PRIMARY KEY,
    [Uid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT UK_Account_Uid UNIQUE,
    [DateCreated] DATETIMEOFFSET NOT NULL CONSTRAINT DF_Account_DateCreated DEFAULT SYSDATETIMEOFFSET(),
);
