CREATE TABLE [accounts].[AccountGroup]
(
	[Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AccountGroup PRIMARY KEY,
    [Uid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT UK_AccountGroup_Uid UNIQUE,
    [DateCreated] DATETIMEOFFSET NOT NULL CONSTRAINT DF_AccountGroup_DateCreated DEFAULT SYSDATETIMEOFFSET(),
);
