CREATE TABLE [categories].[Category]
(
    [Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Category PRIMARY KEY,
    [Uid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT Uk_Category_Uid UNIQUE,
    [DateCreated] DATETIMEOFFSET NOT NULL CONSTRAINT DF_Category_DateCreated DEFAULT SYSDATETIMEOFFSET(),
);
