CREATE TABLE [payees].[Payee]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Payee PRIMARY KEY,
    [Uid] UNIQUEIDENTIFIER NOT NULL CONSTRAINT UK_Payee_Uid UNIQUE,
    [DateCreated] DATETIMEOFFSET NOT NULL CONSTRAINT DF_Payee_DateCreated DEFAULT SYSDATETIMEOFFSET(),
);
