
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - src/WebApi/database/**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild src/WebApi/database/JasonMoney.SSDT/JasonMoney.SSDT.sqlproj --verbosity:diag -property:Configuration=Release
